[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "sigas"
authors = [{name = "Banun Aryani", email = "banunaryani@gmail.com"}]
dynamic = ["terbaru", "dokumentasi SIGAS"]
